### ISSUE TITLE
Line Break Command Unclear

### ISSUE THREAD

**Issue by greetzdk** [throwaway734/Stationmaster#4]
So, line break, how does it work?

`Blah blah blah`
`br`
`Blah blah blah`

Displays as "blah blah blah," new window that says "br" and then, "blah blah"
and

`Blah blah blah`
`<br>`
`Blah blah blah`

displays the same way.

**Comment by ghost** [comment]
To make a line with a break, use Blah blah blah[br]Blah blah blah.
